// Generated by the protocol buffer compiler.  DO NOT EDIT!

package temperance.protobuf;

public final class Map {
  private Map() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage {
    // Use Request.newBuilder() to construct.
    private Request() {}
    
    private static final Request defaultInstance = new Request();
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return temperance.protobuf.Map.internal_static_temperance_protobuf_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return temperance.protobuf.Map.internal_static_temperance_protobuf_Request_fieldAccessorTable;
    }
    
    public static final class Set extends
        com.google.protobuf.GeneratedMessage {
      // Use Set.newBuilder() to construct.
      private Set() {}
      
      private static final Set defaultInstance = new Set();
      public static Set getDefaultInstance() {
        return defaultInstance;
      }
      
      public Set getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temperance.protobuf.Map.internal_static_temperance_protobuf_Request_Set_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temperance.protobuf.Map.internal_static_temperance_protobuf_Request_Set_fieldAccessorTable;
      }
      
      // required string namespace = 1;
      public static final int NAMESPACE_FIELD_NUMBER = 1;
      private boolean hasNamespace;
      private java.lang.String namespace_ = "";
      public boolean hasNamespace() { return hasNamespace; }
      public java.lang.String getNamespace() { return namespace_; }
      
      // required string key = 2;
      public static final int KEY_FIELD_NUMBER = 2;
      private boolean hasKey;
      private java.lang.String key_ = "";
      public boolean hasKey() { return hasKey; }
      public java.lang.String getKey() { return key_; }
      
      // required string value = 3;
      public static final int VALUE_FIELD_NUMBER = 3;
      private boolean hasValue;
      private java.lang.String value_ = "";
      public boolean hasValue() { return hasValue; }
      public java.lang.String getValue() { return value_; }
      
      public final boolean isInitialized() {
        if (!hasNamespace) return false;
        if (!hasKey) return false;
        if (!hasValue) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasNamespace()) {
          output.writeString(1, getNamespace());
        }
        if (hasKey()) {
          output.writeString(2, getKey());
        }
        if (hasValue()) {
          output.writeString(3, getValue());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasNamespace()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getNamespace());
        }
        if (hasKey()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getKey());
        }
        if (hasValue()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(3, getValue());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static temperance.protobuf.Map.Request.Set parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Map.Request.Set parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Map.Request.Set parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Map.Request.Set parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Map.Request.Set parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Map.Request.Set parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Map.Request.Set parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static temperance.protobuf.Map.Request.Set parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Map.Request.Set parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Map.Request.Set parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(temperance.protobuf.Map.Request.Set prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private temperance.protobuf.Map.Request.Set result;
        
        // Construct using temperance.protobuf.Map.Request.Set.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new temperance.protobuf.Map.Request.Set();
          return builder;
        }
        
        protected temperance.protobuf.Map.Request.Set internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new temperance.protobuf.Map.Request.Set();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return temperance.protobuf.Map.Request.Set.getDescriptor();
        }
        
        public temperance.protobuf.Map.Request.Set getDefaultInstanceForType() {
          return temperance.protobuf.Map.Request.Set.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public temperance.protobuf.Map.Request.Set build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private temperance.protobuf.Map.Request.Set buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public temperance.protobuf.Map.Request.Set buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          temperance.protobuf.Map.Request.Set returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof temperance.protobuf.Map.Request.Set) {
            return mergeFrom((temperance.protobuf.Map.Request.Set)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(temperance.protobuf.Map.Request.Set other) {
          if (other == temperance.protobuf.Map.Request.Set.getDefaultInstance()) return this;
          if (other.hasNamespace()) {
            setNamespace(other.getNamespace());
          }
          if (other.hasKey()) {
            setKey(other.getKey());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setNamespace(input.readString());
                break;
              }
              case 18: {
                setKey(input.readString());
                break;
              }
              case 26: {
                setValue(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required string namespace = 1;
        public boolean hasNamespace() {
          return result.hasNamespace();
        }
        public java.lang.String getNamespace() {
          return result.getNamespace();
        }
        public Builder setNamespace(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasNamespace = true;
          result.namespace_ = value;
          return this;
        }
        public Builder clearNamespace() {
          result.hasNamespace = false;
          result.namespace_ = getDefaultInstance().getNamespace();
          return this;
        }
        
        // required string key = 2;
        public boolean hasKey() {
          return result.hasKey();
        }
        public java.lang.String getKey() {
          return result.getKey();
        }
        public Builder setKey(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
          result.key_ = value;
          return this;
        }
        public Builder clearKey() {
          result.hasKey = false;
          result.key_ = getDefaultInstance().getKey();
          return this;
        }
        
        // required string value = 3;
        public boolean hasValue() {
          return result.hasValue();
        }
        public java.lang.String getValue() {
          return result.getValue();
        }
        public Builder setValue(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasValue = true;
          result.value_ = value;
          return this;
        }
        public Builder clearValue() {
          result.hasValue = false;
          result.value_ = getDefaultInstance().getValue();
          return this;
        }
      }
      
      static {
        temperance.protobuf.Map.getDescriptor();
      }
      
      static {
        temperance.protobuf.Map.internalForceInit();
      }
    }
    
    public static final class Get extends
        com.google.protobuf.GeneratedMessage {
      // Use Get.newBuilder() to construct.
      private Get() {}
      
      private static final Get defaultInstance = new Get();
      public static Get getDefaultInstance() {
        return defaultInstance;
      }
      
      public Get getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temperance.protobuf.Map.internal_static_temperance_protobuf_Request_Get_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temperance.protobuf.Map.internal_static_temperance_protobuf_Request_Get_fieldAccessorTable;
      }
      
      // required string namespace = 1;
      public static final int NAMESPACE_FIELD_NUMBER = 1;
      private boolean hasNamespace;
      private java.lang.String namespace_ = "";
      public boolean hasNamespace() { return hasNamespace; }
      public java.lang.String getNamespace() { return namespace_; }
      
      // required string key = 2;
      public static final int KEY_FIELD_NUMBER = 2;
      private boolean hasKey;
      private java.lang.String key_ = "";
      public boolean hasKey() { return hasKey; }
      public java.lang.String getKey() { return key_; }
      
      public final boolean isInitialized() {
        if (!hasNamespace) return false;
        if (!hasKey) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasNamespace()) {
          output.writeString(1, getNamespace());
        }
        if (hasKey()) {
          output.writeString(2, getKey());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasNamespace()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getNamespace());
        }
        if (hasKey()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getKey());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static temperance.protobuf.Map.Request.Get parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Map.Request.Get parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Map.Request.Get parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Map.Request.Get parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Map.Request.Get parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Map.Request.Get parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Map.Request.Get parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static temperance.protobuf.Map.Request.Get parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Map.Request.Get parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Map.Request.Get parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(temperance.protobuf.Map.Request.Get prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private temperance.protobuf.Map.Request.Get result;
        
        // Construct using temperance.protobuf.Map.Request.Get.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new temperance.protobuf.Map.Request.Get();
          return builder;
        }
        
        protected temperance.protobuf.Map.Request.Get internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new temperance.protobuf.Map.Request.Get();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return temperance.protobuf.Map.Request.Get.getDescriptor();
        }
        
        public temperance.protobuf.Map.Request.Get getDefaultInstanceForType() {
          return temperance.protobuf.Map.Request.Get.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public temperance.protobuf.Map.Request.Get build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private temperance.protobuf.Map.Request.Get buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public temperance.protobuf.Map.Request.Get buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          temperance.protobuf.Map.Request.Get returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof temperance.protobuf.Map.Request.Get) {
            return mergeFrom((temperance.protobuf.Map.Request.Get)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(temperance.protobuf.Map.Request.Get other) {
          if (other == temperance.protobuf.Map.Request.Get.getDefaultInstance()) return this;
          if (other.hasNamespace()) {
            setNamespace(other.getNamespace());
          }
          if (other.hasKey()) {
            setKey(other.getKey());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setNamespace(input.readString());
                break;
              }
              case 18: {
                setKey(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required string namespace = 1;
        public boolean hasNamespace() {
          return result.hasNamespace();
        }
        public java.lang.String getNamespace() {
          return result.getNamespace();
        }
        public Builder setNamespace(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasNamespace = true;
          result.namespace_ = value;
          return this;
        }
        public Builder clearNamespace() {
          result.hasNamespace = false;
          result.namespace_ = getDefaultInstance().getNamespace();
          return this;
        }
        
        // required string key = 2;
        public boolean hasKey() {
          return result.hasKey();
        }
        public java.lang.String getKey() {
          return result.getKey();
        }
        public Builder setKey(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
          result.key_ = value;
          return this;
        }
        public Builder clearKey() {
          result.hasKey = false;
          result.key_ = getDefaultInstance().getKey();
          return this;
        }
      }
      
      static {
        temperance.protobuf.Map.getDescriptor();
      }
      
      static {
        temperance.protobuf.Map.internalForceInit();
      }
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static temperance.protobuf.Map.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Map.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Map.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Map.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Map.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Map.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Map.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static temperance.protobuf.Map.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Map.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Map.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(temperance.protobuf.Map.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private temperance.protobuf.Map.Request result;
      
      // Construct using temperance.protobuf.Map.Request.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new temperance.protobuf.Map.Request();
        return builder;
      }
      
      protected temperance.protobuf.Map.Request internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new temperance.protobuf.Map.Request();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return temperance.protobuf.Map.Request.getDescriptor();
      }
      
      public temperance.protobuf.Map.Request getDefaultInstanceForType() {
        return temperance.protobuf.Map.Request.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public temperance.protobuf.Map.Request build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private temperance.protobuf.Map.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public temperance.protobuf.Map.Request buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        temperance.protobuf.Map.Request returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof temperance.protobuf.Map.Request) {
          return mergeFrom((temperance.protobuf.Map.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(temperance.protobuf.Map.Request other) {
        if (other == temperance.protobuf.Map.Request.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
    }
    
    static {
      temperance.protobuf.Map.getDescriptor();
    }
    
    static {
      temperance.protobuf.Map.internalForceInit();
    }
  }
  
  public static final class Response extends
      com.google.protobuf.GeneratedMessage {
    // Use Response.newBuilder() to construct.
    private Response() {}
    
    private static final Response defaultInstance = new Response();
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return temperance.protobuf.Map.internal_static_temperance_protobuf_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return temperance.protobuf.Map.internal_static_temperance_protobuf_Response_fieldAccessorTable;
    }
    
    public static final class Set extends
        com.google.protobuf.GeneratedMessage {
      // Use Set.newBuilder() to construct.
      private Set() {}
      
      private static final Set defaultInstance = new Set();
      public static Set getDefaultInstance() {
        return defaultInstance;
      }
      
      public Set getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temperance.protobuf.Map.internal_static_temperance_protobuf_Response_Set_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temperance.protobuf.Map.internal_static_temperance_protobuf_Response_Set_fieldAccessorTable;
      }
      
      // required bool succeed = 1;
      public static final int SUCCEED_FIELD_NUMBER = 1;
      private boolean hasSucceed;
      private boolean succeed_ = false;
      public boolean hasSucceed() { return hasSucceed; }
      public boolean getSucceed() { return succeed_; }
      
      public final boolean isInitialized() {
        if (!hasSucceed) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasSucceed()) {
          output.writeBool(1, getSucceed());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasSucceed()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(1, getSucceed());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static temperance.protobuf.Map.Response.Set parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Map.Response.Set parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Map.Response.Set parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Map.Response.Set parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Map.Response.Set parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Map.Response.Set parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Map.Response.Set parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static temperance.protobuf.Map.Response.Set parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Map.Response.Set parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Map.Response.Set parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(temperance.protobuf.Map.Response.Set prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private temperance.protobuf.Map.Response.Set result;
        
        // Construct using temperance.protobuf.Map.Response.Set.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new temperance.protobuf.Map.Response.Set();
          return builder;
        }
        
        protected temperance.protobuf.Map.Response.Set internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new temperance.protobuf.Map.Response.Set();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return temperance.protobuf.Map.Response.Set.getDescriptor();
        }
        
        public temperance.protobuf.Map.Response.Set getDefaultInstanceForType() {
          return temperance.protobuf.Map.Response.Set.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public temperance.protobuf.Map.Response.Set build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private temperance.protobuf.Map.Response.Set buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public temperance.protobuf.Map.Response.Set buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          temperance.protobuf.Map.Response.Set returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof temperance.protobuf.Map.Response.Set) {
            return mergeFrom((temperance.protobuf.Map.Response.Set)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(temperance.protobuf.Map.Response.Set other) {
          if (other == temperance.protobuf.Map.Response.Set.getDefaultInstance()) return this;
          if (other.hasSucceed()) {
            setSucceed(other.getSucceed());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 8: {
                setSucceed(input.readBool());
                break;
              }
            }
          }
        }
        
        
        // required bool succeed = 1;
        public boolean hasSucceed() {
          return result.hasSucceed();
        }
        public boolean getSucceed() {
          return result.getSucceed();
        }
        public Builder setSucceed(boolean value) {
          result.hasSucceed = true;
          result.succeed_ = value;
          return this;
        }
        public Builder clearSucceed() {
          result.hasSucceed = false;
          result.succeed_ = false;
          return this;
        }
      }
      
      static {
        temperance.protobuf.Map.getDescriptor();
      }
      
      static {
        temperance.protobuf.Map.internalForceInit();
      }
    }
    
    public static final class Get extends
        com.google.protobuf.GeneratedMessage {
      // Use Get.newBuilder() to construct.
      private Get() {}
      
      private static final Get defaultInstance = new Get();
      public static Get getDefaultInstance() {
        return defaultInstance;
      }
      
      public Get getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temperance.protobuf.Map.internal_static_temperance_protobuf_Response_Get_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temperance.protobuf.Map.internal_static_temperance_protobuf_Response_Get_fieldAccessorTable;
      }
      
      // required string value = 1;
      public static final int VALUE_FIELD_NUMBER = 1;
      private boolean hasValue;
      private java.lang.String value_ = "";
      public boolean hasValue() { return hasValue; }
      public java.lang.String getValue() { return value_; }
      
      public final boolean isInitialized() {
        if (!hasValue) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasValue()) {
          output.writeString(1, getValue());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasValue()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getValue());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static temperance.protobuf.Map.Response.Get parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Map.Response.Get parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Map.Response.Get parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Map.Response.Get parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Map.Response.Get parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Map.Response.Get parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Map.Response.Get parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static temperance.protobuf.Map.Response.Get parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Map.Response.Get parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Map.Response.Get parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(temperance.protobuf.Map.Response.Get prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private temperance.protobuf.Map.Response.Get result;
        
        // Construct using temperance.protobuf.Map.Response.Get.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new temperance.protobuf.Map.Response.Get();
          return builder;
        }
        
        protected temperance.protobuf.Map.Response.Get internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new temperance.protobuf.Map.Response.Get();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return temperance.protobuf.Map.Response.Get.getDescriptor();
        }
        
        public temperance.protobuf.Map.Response.Get getDefaultInstanceForType() {
          return temperance.protobuf.Map.Response.Get.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public temperance.protobuf.Map.Response.Get build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private temperance.protobuf.Map.Response.Get buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public temperance.protobuf.Map.Response.Get buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          temperance.protobuf.Map.Response.Get returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof temperance.protobuf.Map.Response.Get) {
            return mergeFrom((temperance.protobuf.Map.Response.Get)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(temperance.protobuf.Map.Response.Get other) {
          if (other == temperance.protobuf.Map.Response.Get.getDefaultInstance()) return this;
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setValue(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required string value = 1;
        public boolean hasValue() {
          return result.hasValue();
        }
        public java.lang.String getValue() {
          return result.getValue();
        }
        public Builder setValue(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasValue = true;
          result.value_ = value;
          return this;
        }
        public Builder clearValue() {
          result.hasValue = false;
          result.value_ = getDefaultInstance().getValue();
          return this;
        }
      }
      
      static {
        temperance.protobuf.Map.getDescriptor();
      }
      
      static {
        temperance.protobuf.Map.internalForceInit();
      }
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static temperance.protobuf.Map.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Map.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Map.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Map.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Map.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Map.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Map.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static temperance.protobuf.Map.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Map.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Map.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(temperance.protobuf.Map.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private temperance.protobuf.Map.Response result;
      
      // Construct using temperance.protobuf.Map.Response.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new temperance.protobuf.Map.Response();
        return builder;
      }
      
      protected temperance.protobuf.Map.Response internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new temperance.protobuf.Map.Response();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return temperance.protobuf.Map.Response.getDescriptor();
      }
      
      public temperance.protobuf.Map.Response getDefaultInstanceForType() {
        return temperance.protobuf.Map.Response.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public temperance.protobuf.Map.Response build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private temperance.protobuf.Map.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public temperance.protobuf.Map.Response buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        temperance.protobuf.Map.Response returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof temperance.protobuf.Map.Response) {
          return mergeFrom((temperance.protobuf.Map.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(temperance.protobuf.Map.Response other) {
        if (other == temperance.protobuf.Map.Response.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
    }
    
    static {
      temperance.protobuf.Map.getDescriptor();
    }
    
    static {
      temperance.protobuf.Map.internalForceInit();
    }
  }
  
  public static abstract class MapService
      implements com.google.protobuf.Service {
    protected MapService() {}
    
    public interface Interface {
      public abstract void set(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Map.Request.Set request,
          com.google.protobuf.RpcCallback<temperance.protobuf.Map.Response.Set> done);
      
      public abstract void get(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Map.Request.Get request,
          com.google.protobuf.RpcCallback<temperance.protobuf.Map.Response.Get> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new MapService() {
        @Override
        public  void set(
            com.google.protobuf.RpcController controller,
            temperance.protobuf.Map.Request.Set request,
            com.google.protobuf.RpcCallback<temperance.protobuf.Map.Response.Set> done) {
          impl.set(controller, request, done);
        }
        
        @Override
        public  void get(
            com.google.protobuf.RpcController controller,
            temperance.protobuf.Map.Request.Get request,
            com.google.protobuf.RpcCallback<temperance.protobuf.Map.Response.Get> done) {
          impl.get(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.set(controller, (temperance.protobuf.Map.Request.Set)request);
            case 1:
              return impl.get(controller, (temperance.protobuf.Map.Request.Get)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return temperance.protobuf.Map.Request.Set.getDefaultInstance();
            case 1:
              return temperance.protobuf.Map.Request.Get.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return temperance.protobuf.Map.Response.Set.getDefaultInstance();
            case 1:
              return temperance.protobuf.Map.Response.Get.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void set(
        com.google.protobuf.RpcController controller,
        temperance.protobuf.Map.Request.Set request,
        com.google.protobuf.RpcCallback<temperance.protobuf.Map.Response.Set> done);
    
    public abstract void get(
        com.google.protobuf.RpcController controller,
        temperance.protobuf.Map.Request.Get request,
        com.google.protobuf.RpcCallback<temperance.protobuf.Map.Response.Get> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return temperance.protobuf.Map.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.set(controller, (temperance.protobuf.Map.Request.Set)request,
            com.google.protobuf.RpcUtil.<temperance.protobuf.Map.Response.Set>specializeCallback(
              done));
          return;
        case 1:
          this.get(controller, (temperance.protobuf.Map.Request.Get)request,
            com.google.protobuf.RpcUtil.<temperance.protobuf.Map.Response.Get>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return temperance.protobuf.Map.Request.Set.getDefaultInstance();
        case 1:
          return temperance.protobuf.Map.Request.Get.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return temperance.protobuf.Map.Response.Set.getDefaultInstance();
        case 1:
          return temperance.protobuf.Map.Response.Get.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends temperance.protobuf.Map.MapService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void set(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Map.Request.Set request,
          com.google.protobuf.RpcCallback<temperance.protobuf.Map.Response.Set> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          temperance.protobuf.Map.Response.Set.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            temperance.protobuf.Map.Response.Set.class,
            temperance.protobuf.Map.Response.Set.getDefaultInstance()));
      }
      
      public  void get(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Map.Request.Get request,
          com.google.protobuf.RpcCallback<temperance.protobuf.Map.Response.Get> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          temperance.protobuf.Map.Response.Get.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            temperance.protobuf.Map.Response.Get.class,
            temperance.protobuf.Map.Response.Get.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public temperance.protobuf.Map.Response.Set set(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Map.Request.Set request)
          throws com.google.protobuf.ServiceException;
      
      public temperance.protobuf.Map.Response.Get get(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Map.Request.Get request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public temperance.protobuf.Map.Response.Set set(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Map.Request.Set request)
          throws com.google.protobuf.ServiceException {
        return (temperance.protobuf.Map.Response.Set) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          temperance.protobuf.Map.Response.Set.getDefaultInstance());
      }
      
      
      public temperance.protobuf.Map.Response.Get get(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Map.Request.Get request)
          throws com.google.protobuf.ServiceException {
        return (temperance.protobuf.Map.Response.Get) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          temperance.protobuf.Map.Response.Get.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Request_Set_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Request_Set_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Request_Get_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Request_Get_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Response_Set_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Response_Set_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Response_Get_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Response_Get_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tMap.proto\022\023temperance.protobuf\"f\n\007Requ" +
      "est\0324\n\003Set\022\021\n\tnamespace\030\001 \002(\t\022\013\n\003key\030\002 \002" +
      "(\t\022\r\n\005value\030\003 \002(\t\032%\n\003Get\022\021\n\tnamespace\030\001 " +
      "\002(\t\022\013\n\003key\030\002 \002(\t\"8\n\010Response\032\026\n\003Set\022\017\n\007s" +
      "ucceed\030\001 \002(\010\032\024\n\003Get\022\r\n\005value\030\001 \002(\t2\244\001\n\nM" +
      "apService\022J\n\003set\022 .temperance.protobuf.R" +
      "equest.Set\032!.temperance.protobuf.Respons" +
      "e.Set\022J\n\003get\022 .temperance.protobuf.Reque" +
      "st.Get\032!.temperance.protobuf.Response.Ge" +
      "tB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_temperance_protobuf_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_temperance_protobuf_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Request_descriptor,
              new java.lang.String[] { },
              temperance.protobuf.Map.Request.class,
              temperance.protobuf.Map.Request.Builder.class);
          internal_static_temperance_protobuf_Request_Set_descriptor =
            internal_static_temperance_protobuf_Request_descriptor.getNestedTypes().get(0);
          internal_static_temperance_protobuf_Request_Set_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Request_Set_descriptor,
              new java.lang.String[] { "Namespace", "Key", "Value", },
              temperance.protobuf.Map.Request.Set.class,
              temperance.protobuf.Map.Request.Set.Builder.class);
          internal_static_temperance_protobuf_Request_Get_descriptor =
            internal_static_temperance_protobuf_Request_descriptor.getNestedTypes().get(1);
          internal_static_temperance_protobuf_Request_Get_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Request_Get_descriptor,
              new java.lang.String[] { "Namespace", "Key", },
              temperance.protobuf.Map.Request.Get.class,
              temperance.protobuf.Map.Request.Get.Builder.class);
          internal_static_temperance_protobuf_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_temperance_protobuf_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Response_descriptor,
              new java.lang.String[] { },
              temperance.protobuf.Map.Response.class,
              temperance.protobuf.Map.Response.Builder.class);
          internal_static_temperance_protobuf_Response_Set_descriptor =
            internal_static_temperance_protobuf_Response_descriptor.getNestedTypes().get(0);
          internal_static_temperance_protobuf_Response_Set_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Response_Set_descriptor,
              new java.lang.String[] { "Succeed", },
              temperance.protobuf.Map.Response.Set.class,
              temperance.protobuf.Map.Response.Set.Builder.class);
          internal_static_temperance_protobuf_Response_Get_descriptor =
            internal_static_temperance_protobuf_Response_descriptor.getNestedTypes().get(1);
          internal_static_temperance_protobuf_Response_Get_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Response_Get_descriptor,
              new java.lang.String[] { "Value", },
              temperance.protobuf.Map.Response.Get.class,
              temperance.protobuf.Map.Response.Get.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
