// Generated by the protocol buffer compiler.  DO NOT EDIT!

package temperance.protobuf;

public final class Mecab {
  private Mecab() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage {
    // Use Request.newBuilder() to construct.
    private Request() {}
    
    private static final Request defaultInstance = new Request();
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return temperance.protobuf.Mecab.internal_static_temperance_protobuf_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return temperance.protobuf.Mecab.internal_static_temperance_protobuf_Request_fieldAccessorTable;
    }
    
    public static final class Parse extends
        com.google.protobuf.GeneratedMessage {
      // Use Parse.newBuilder() to construct.
      private Parse() {}
      
      private static final Parse defaultInstance = new Parse();
      public static Parse getDefaultInstance() {
        return defaultInstance;
      }
      
      public Parse getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temperance.protobuf.Mecab.internal_static_temperance_protobuf_Request_Parse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temperance.protobuf.Mecab.internal_static_temperance_protobuf_Request_Parse_fieldAccessorTable;
      }
      
      // required string str = 1;
      public static final int STR_FIELD_NUMBER = 1;
      private boolean hasStr;
      private java.lang.String str_ = "";
      public boolean hasStr() { return hasStr; }
      public java.lang.String getStr() { return str_; }
      
      public final boolean isInitialized() {
        if (!hasStr) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasStr()) {
          output.writeString(1, getStr());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasStr()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getStr());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static temperance.protobuf.Mecab.Request.Parse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Mecab.Request.Parse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Mecab.Request.Parse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Mecab.Request.Parse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Mecab.Request.Parse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Mecab.Request.Parse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Mecab.Request.Parse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static temperance.protobuf.Mecab.Request.Parse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Mecab.Request.Parse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Mecab.Request.Parse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(temperance.protobuf.Mecab.Request.Parse prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private temperance.protobuf.Mecab.Request.Parse result;
        
        // Construct using temperance.protobuf.Mecab.Request.Parse.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new temperance.protobuf.Mecab.Request.Parse();
          return builder;
        }
        
        protected temperance.protobuf.Mecab.Request.Parse internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new temperance.protobuf.Mecab.Request.Parse();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return temperance.protobuf.Mecab.Request.Parse.getDescriptor();
        }
        
        public temperance.protobuf.Mecab.Request.Parse getDefaultInstanceForType() {
          return temperance.protobuf.Mecab.Request.Parse.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public temperance.protobuf.Mecab.Request.Parse build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private temperance.protobuf.Mecab.Request.Parse buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public temperance.protobuf.Mecab.Request.Parse buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          temperance.protobuf.Mecab.Request.Parse returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof temperance.protobuf.Mecab.Request.Parse) {
            return mergeFrom((temperance.protobuf.Mecab.Request.Parse)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(temperance.protobuf.Mecab.Request.Parse other) {
          if (other == temperance.protobuf.Mecab.Request.Parse.getDefaultInstance()) return this;
          if (other.hasStr()) {
            setStr(other.getStr());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setStr(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required string str = 1;
        public boolean hasStr() {
          return result.hasStr();
        }
        public java.lang.String getStr() {
          return result.getStr();
        }
        public Builder setStr(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasStr = true;
          result.str_ = value;
          return this;
        }
        public Builder clearStr() {
          result.hasStr = false;
          result.str_ = getDefaultInstance().getStr();
          return this;
        }
      }
      
      static {
        temperance.protobuf.Mecab.getDescriptor();
      }
      
      static {
        temperance.protobuf.Mecab.internalForceInit();
      }
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static temperance.protobuf.Mecab.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Mecab.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Mecab.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Mecab.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Mecab.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Mecab.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Mecab.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static temperance.protobuf.Mecab.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Mecab.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Mecab.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(temperance.protobuf.Mecab.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private temperance.protobuf.Mecab.Request result;
      
      // Construct using temperance.protobuf.Mecab.Request.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new temperance.protobuf.Mecab.Request();
        return builder;
      }
      
      protected temperance.protobuf.Mecab.Request internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new temperance.protobuf.Mecab.Request();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return temperance.protobuf.Mecab.Request.getDescriptor();
      }
      
      public temperance.protobuf.Mecab.Request getDefaultInstanceForType() {
        return temperance.protobuf.Mecab.Request.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public temperance.protobuf.Mecab.Request build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private temperance.protobuf.Mecab.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public temperance.protobuf.Mecab.Request buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        temperance.protobuf.Mecab.Request returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof temperance.protobuf.Mecab.Request) {
          return mergeFrom((temperance.protobuf.Mecab.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(temperance.protobuf.Mecab.Request other) {
        if (other == temperance.protobuf.Mecab.Request.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
    }
    
    static {
      temperance.protobuf.Mecab.getDescriptor();
    }
    
    static {
      temperance.protobuf.Mecab.internalForceInit();
    }
  }
  
  public static final class Response extends
      com.google.protobuf.GeneratedMessage {
    // Use Response.newBuilder() to construct.
    private Response() {}
    
    private static final Response defaultInstance = new Response();
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return temperance.protobuf.Mecab.internal_static_temperance_protobuf_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return temperance.protobuf.Mecab.internal_static_temperance_protobuf_Response_fieldAccessorTable;
    }
    
    public static final class Node extends
        com.google.protobuf.GeneratedMessage {
      // Use Node.newBuilder() to construct.
      private Node() {}
      
      private static final Node defaultInstance = new Node();
      public static Node getDefaultInstance() {
        return defaultInstance;
      }
      
      public Node getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temperance.protobuf.Mecab.internal_static_temperance_protobuf_Response_Node_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temperance.protobuf.Mecab.internal_static_temperance_protobuf_Response_Node_fieldAccessorTable;
      }
      
      // required string surface = 1;
      public static final int SURFACE_FIELD_NUMBER = 1;
      private boolean hasSurface;
      private java.lang.String surface_ = "";
      public boolean hasSurface() { return hasSurface; }
      public java.lang.String getSurface() { return surface_; }
      
      // required string feature = 2;
      public static final int FEATURE_FIELD_NUMBER = 2;
      private boolean hasFeature;
      private java.lang.String feature_ = "";
      public boolean hasFeature() { return hasFeature; }
      public java.lang.String getFeature() { return feature_; }
      
      public final boolean isInitialized() {
        if (!hasSurface) return false;
        if (!hasFeature) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasSurface()) {
          output.writeString(1, getSurface());
        }
        if (hasFeature()) {
          output.writeString(2, getFeature());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasSurface()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getSurface());
        }
        if (hasFeature()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getFeature());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static temperance.protobuf.Mecab.Response.Node parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Node parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Node parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Node parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Node parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Node parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Node parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Node parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Node parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Node parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(temperance.protobuf.Mecab.Response.Node prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private temperance.protobuf.Mecab.Response.Node result;
        
        // Construct using temperance.protobuf.Mecab.Response.Node.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new temperance.protobuf.Mecab.Response.Node();
          return builder;
        }
        
        protected temperance.protobuf.Mecab.Response.Node internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new temperance.protobuf.Mecab.Response.Node();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return temperance.protobuf.Mecab.Response.Node.getDescriptor();
        }
        
        public temperance.protobuf.Mecab.Response.Node getDefaultInstanceForType() {
          return temperance.protobuf.Mecab.Response.Node.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public temperance.protobuf.Mecab.Response.Node build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private temperance.protobuf.Mecab.Response.Node buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public temperance.protobuf.Mecab.Response.Node buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          temperance.protobuf.Mecab.Response.Node returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof temperance.protobuf.Mecab.Response.Node) {
            return mergeFrom((temperance.protobuf.Mecab.Response.Node)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(temperance.protobuf.Mecab.Response.Node other) {
          if (other == temperance.protobuf.Mecab.Response.Node.getDefaultInstance()) return this;
          if (other.hasSurface()) {
            setSurface(other.getSurface());
          }
          if (other.hasFeature()) {
            setFeature(other.getFeature());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setSurface(input.readString());
                break;
              }
              case 18: {
                setFeature(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required string surface = 1;
        public boolean hasSurface() {
          return result.hasSurface();
        }
        public java.lang.String getSurface() {
          return result.getSurface();
        }
        public Builder setSurface(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasSurface = true;
          result.surface_ = value;
          return this;
        }
        public Builder clearSurface() {
          result.hasSurface = false;
          result.surface_ = getDefaultInstance().getSurface();
          return this;
        }
        
        // required string feature = 2;
        public boolean hasFeature() {
          return result.hasFeature();
        }
        public java.lang.String getFeature() {
          return result.getFeature();
        }
        public Builder setFeature(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasFeature = true;
          result.feature_ = value;
          return this;
        }
        public Builder clearFeature() {
          result.hasFeature = false;
          result.feature_ = getDefaultInstance().getFeature();
          return this;
        }
      }
      
      static {
        temperance.protobuf.Mecab.getDescriptor();
      }
      
      static {
        temperance.protobuf.Mecab.internalForceInit();
      }
    }
    
    public static final class Parse extends
        com.google.protobuf.GeneratedMessage {
      // Use Parse.newBuilder() to construct.
      private Parse() {}
      
      private static final Parse defaultInstance = new Parse();
      public static Parse getDefaultInstance() {
        return defaultInstance;
      }
      
      public Parse getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temperance.protobuf.Mecab.internal_static_temperance_protobuf_Response_Parse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temperance.protobuf.Mecab.internal_static_temperance_protobuf_Response_Parse_fieldAccessorTable;
      }
      
      // repeated .temperance.protobuf.Response.Node nodes = 1;
      public static final int NODES_FIELD_NUMBER = 1;
      private java.util.List<temperance.protobuf.Mecab.Response.Node> nodes_ =
        java.util.Collections.emptyList();
      public java.util.List<temperance.protobuf.Mecab.Response.Node> getNodesList() {
        return nodes_;
      }
      public int getNodesCount() { return nodes_.size(); }
      public temperance.protobuf.Mecab.Response.Node getNodes(int index) {
        return nodes_.get(index);
      }
      
      public final boolean isInitialized() {
        for (temperance.protobuf.Mecab.Response.Node element : getNodesList()) {
          if (!element.isInitialized()) return false;
        }
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (temperance.protobuf.Mecab.Response.Node element : getNodesList()) {
          output.writeMessage(1, element);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        for (temperance.protobuf.Mecab.Response.Node element : getNodesList()) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, element);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static temperance.protobuf.Mecab.Response.Parse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Parse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Parse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Parse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Parse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Parse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Parse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Parse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Parse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Mecab.Response.Parse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(temperance.protobuf.Mecab.Response.Parse prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private temperance.protobuf.Mecab.Response.Parse result;
        
        // Construct using temperance.protobuf.Mecab.Response.Parse.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new temperance.protobuf.Mecab.Response.Parse();
          return builder;
        }
        
        protected temperance.protobuf.Mecab.Response.Parse internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new temperance.protobuf.Mecab.Response.Parse();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return temperance.protobuf.Mecab.Response.Parse.getDescriptor();
        }
        
        public temperance.protobuf.Mecab.Response.Parse getDefaultInstanceForType() {
          return temperance.protobuf.Mecab.Response.Parse.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public temperance.protobuf.Mecab.Response.Parse build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private temperance.protobuf.Mecab.Response.Parse buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public temperance.protobuf.Mecab.Response.Parse buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          if (result.nodes_ != java.util.Collections.EMPTY_LIST) {
            result.nodes_ =
              java.util.Collections.unmodifiableList(result.nodes_);
          }
          temperance.protobuf.Mecab.Response.Parse returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof temperance.protobuf.Mecab.Response.Parse) {
            return mergeFrom((temperance.protobuf.Mecab.Response.Parse)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(temperance.protobuf.Mecab.Response.Parse other) {
          if (other == temperance.protobuf.Mecab.Response.Parse.getDefaultInstance()) return this;
          if (!other.nodes_.isEmpty()) {
            if (result.nodes_.isEmpty()) {
              result.nodes_ = new java.util.ArrayList<temperance.protobuf.Mecab.Response.Node>();
            }
            result.nodes_.addAll(other.nodes_);
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                temperance.protobuf.Mecab.Response.Node.Builder subBuilder = temperance.protobuf.Mecab.Response.Node.newBuilder();
                input.readMessage(subBuilder, extensionRegistry);
                addNodes(subBuilder.buildPartial());
                break;
              }
            }
          }
        }
        
        
        // repeated .temperance.protobuf.Response.Node nodes = 1;
        public java.util.List<temperance.protobuf.Mecab.Response.Node> getNodesList() {
          return java.util.Collections.unmodifiableList(result.nodes_);
        }
        public int getNodesCount() {
          return result.getNodesCount();
        }
        public temperance.protobuf.Mecab.Response.Node getNodes(int index) {
          return result.getNodes(index);
        }
        public Builder setNodes(int index, temperance.protobuf.Mecab.Response.Node value) {
          if (value == null) {
            throw new NullPointerException();
          }
          result.nodes_.set(index, value);
          return this;
        }
        public Builder setNodes(int index, temperance.protobuf.Mecab.Response.Node.Builder builderForValue) {
          result.nodes_.set(index, builderForValue.build());
          return this;
        }
        public Builder addNodes(temperance.protobuf.Mecab.Response.Node value) {
          if (value == null) {
            throw new NullPointerException();
          }
          if (result.nodes_.isEmpty()) {
            result.nodes_ = new java.util.ArrayList<temperance.protobuf.Mecab.Response.Node>();
          }
          result.nodes_.add(value);
          return this;
        }
        public Builder addNodes(temperance.protobuf.Mecab.Response.Node.Builder builderForValue) {
          if (result.nodes_.isEmpty()) {
            result.nodes_ = new java.util.ArrayList<temperance.protobuf.Mecab.Response.Node>();
          }
          result.nodes_.add(builderForValue.build());
          return this;
        }
        public Builder addAllNodes(
            java.lang.Iterable<? extends temperance.protobuf.Mecab.Response.Node> values) {
          if (result.nodes_.isEmpty()) {
            result.nodes_ = new java.util.ArrayList<temperance.protobuf.Mecab.Response.Node>();
          }
          super.addAll(values, result.nodes_);
          return this;
        }
        public Builder clearNodes() {
          result.nodes_ = java.util.Collections.emptyList();
          return this;
        }
      }
      
      static {
        temperance.protobuf.Mecab.getDescriptor();
      }
      
      static {
        temperance.protobuf.Mecab.internalForceInit();
      }
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static temperance.protobuf.Mecab.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Mecab.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Mecab.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Mecab.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Mecab.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Mecab.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Mecab.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static temperance.protobuf.Mecab.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Mecab.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Mecab.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(temperance.protobuf.Mecab.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private temperance.protobuf.Mecab.Response result;
      
      // Construct using temperance.protobuf.Mecab.Response.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new temperance.protobuf.Mecab.Response();
        return builder;
      }
      
      protected temperance.protobuf.Mecab.Response internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new temperance.protobuf.Mecab.Response();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return temperance.protobuf.Mecab.Response.getDescriptor();
      }
      
      public temperance.protobuf.Mecab.Response getDefaultInstanceForType() {
        return temperance.protobuf.Mecab.Response.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public temperance.protobuf.Mecab.Response build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private temperance.protobuf.Mecab.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public temperance.protobuf.Mecab.Response buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        temperance.protobuf.Mecab.Response returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof temperance.protobuf.Mecab.Response) {
          return mergeFrom((temperance.protobuf.Mecab.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(temperance.protobuf.Mecab.Response other) {
        if (other == temperance.protobuf.Mecab.Response.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
    }
    
    static {
      temperance.protobuf.Mecab.getDescriptor();
    }
    
    static {
      temperance.protobuf.Mecab.internalForceInit();
    }
  }
  
  public static abstract class MecabService
      implements com.google.protobuf.Service {
    protected MecabService() {}
    
    public interface Interface {
      public abstract void parse(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Mecab.Request.Parse request,
          com.google.protobuf.RpcCallback<temperance.protobuf.Mecab.Response.Parse> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new MecabService() {
        @Override
        public  void parse(
            com.google.protobuf.RpcController controller,
            temperance.protobuf.Mecab.Request.Parse request,
            com.google.protobuf.RpcCallback<temperance.protobuf.Mecab.Response.Parse> done) {
          impl.parse(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.parse(controller, (temperance.protobuf.Mecab.Request.Parse)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return temperance.protobuf.Mecab.Request.Parse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return temperance.protobuf.Mecab.Response.Parse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void parse(
        com.google.protobuf.RpcController controller,
        temperance.protobuf.Mecab.Request.Parse request,
        com.google.protobuf.RpcCallback<temperance.protobuf.Mecab.Response.Parse> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return temperance.protobuf.Mecab.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.parse(controller, (temperance.protobuf.Mecab.Request.Parse)request,
            com.google.protobuf.RpcUtil.<temperance.protobuf.Mecab.Response.Parse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return temperance.protobuf.Mecab.Request.Parse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return temperance.protobuf.Mecab.Response.Parse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends temperance.protobuf.Mecab.MecabService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void parse(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Mecab.Request.Parse request,
          com.google.protobuf.RpcCallback<temperance.protobuf.Mecab.Response.Parse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          temperance.protobuf.Mecab.Response.Parse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            temperance.protobuf.Mecab.Response.Parse.class,
            temperance.protobuf.Mecab.Response.Parse.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public temperance.protobuf.Mecab.Response.Parse parse(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Mecab.Request.Parse request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public temperance.protobuf.Mecab.Response.Parse parse(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Mecab.Request.Parse request)
          throws com.google.protobuf.ServiceException {
        return (temperance.protobuf.Mecab.Response.Parse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          temperance.protobuf.Mecab.Response.Parse.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Request_Parse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Request_Parse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Response_Node_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Response_Node_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Response_Parse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Response_Parse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Mecab.proto\022\023temperance.protobuf\"\037\n\007Re" +
      "quest\032\024\n\005Parse\022\013\n\003str\030\001 \002(\t\"p\n\010Response\032" +
      "(\n\004Node\022\017\n\007surface\030\001 \002(\t\022\017\n\007feature\030\002 \002(" +
      "\t\032:\n\005Parse\0221\n\005nodes\030\001 \003(\0132\".temperance.p" +
      "rotobuf.Response.Node2`\n\014MecabService\022P\n" +
      "\005parse\022\".temperance.protobuf.Request.Par" +
      "se\032#.temperance.protobuf.Response.ParseB" +
      "\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_temperance_protobuf_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_temperance_protobuf_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Request_descriptor,
              new java.lang.String[] { },
              temperance.protobuf.Mecab.Request.class,
              temperance.protobuf.Mecab.Request.Builder.class);
          internal_static_temperance_protobuf_Request_Parse_descriptor =
            internal_static_temperance_protobuf_Request_descriptor.getNestedTypes().get(0);
          internal_static_temperance_protobuf_Request_Parse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Request_Parse_descriptor,
              new java.lang.String[] { "Str", },
              temperance.protobuf.Mecab.Request.Parse.class,
              temperance.protobuf.Mecab.Request.Parse.Builder.class);
          internal_static_temperance_protobuf_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_temperance_protobuf_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Response_descriptor,
              new java.lang.String[] { },
              temperance.protobuf.Mecab.Response.class,
              temperance.protobuf.Mecab.Response.Builder.class);
          internal_static_temperance_protobuf_Response_Node_descriptor =
            internal_static_temperance_protobuf_Response_descriptor.getNestedTypes().get(0);
          internal_static_temperance_protobuf_Response_Node_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Response_Node_descriptor,
              new java.lang.String[] { "Surface", "Feature", },
              temperance.protobuf.Mecab.Response.Node.class,
              temperance.protobuf.Mecab.Response.Node.Builder.class);
          internal_static_temperance_protobuf_Response_Parse_descriptor =
            internal_static_temperance_protobuf_Response_descriptor.getNestedTypes().get(1);
          internal_static_temperance_protobuf_Response_Parse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Response_Parse_descriptor,
              new java.lang.String[] { "Nodes", },
              temperance.protobuf.Mecab.Response.Parse.class,
              temperance.protobuf.Mecab.Response.Parse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
