// Generated by the protocol buffer compiler.  DO NOT EDIT!

package temperance.protobuf;

public final class Query {
  private Query() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage {
    // Use Request.newBuilder() to construct.
    private Request() {}
    
    private static final Request defaultInstance = new Request();
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return temperance.protobuf.Query.internal_static_temperance_protobuf_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return temperance.protobuf.Query.internal_static_temperance_protobuf_Request_fieldAccessorTable;
    }
    
    public static final class Get extends
        com.google.protobuf.GeneratedMessage {
      // Use Get.newBuilder() to construct.
      private Get() {}
      
      private static final Get defaultInstance = new Get();
      public static Get getDefaultInstance() {
        return defaultInstance;
      }
      
      public Get getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temperance.protobuf.Query.internal_static_temperance_protobuf_Request_Get_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temperance.protobuf.Query.internal_static_temperance_protobuf_Request_Get_fieldAccessorTable;
      }
      
      // required string query = 1;
      public static final int QUERY_FIELD_NUMBER = 1;
      private boolean hasQuery;
      private java.lang.String query_ = "";
      public boolean hasQuery() { return hasQuery; }
      public java.lang.String getQuery() { return query_; }
      
      public final boolean isInitialized() {
        if (!hasQuery) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasQuery()) {
          output.writeString(1, getQuery());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasQuery()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getQuery());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static temperance.protobuf.Query.Request.Get parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Query.Request.Get parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Query.Request.Get parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Query.Request.Get parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Query.Request.Get parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Query.Request.Get parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Query.Request.Get parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static temperance.protobuf.Query.Request.Get parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Query.Request.Get parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Query.Request.Get parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(temperance.protobuf.Query.Request.Get prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private temperance.protobuf.Query.Request.Get result;
        
        // Construct using temperance.protobuf.Query.Request.Get.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new temperance.protobuf.Query.Request.Get();
          return builder;
        }
        
        protected temperance.protobuf.Query.Request.Get internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new temperance.protobuf.Query.Request.Get();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return temperance.protobuf.Query.Request.Get.getDescriptor();
        }
        
        public temperance.protobuf.Query.Request.Get getDefaultInstanceForType() {
          return temperance.protobuf.Query.Request.Get.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public temperance.protobuf.Query.Request.Get build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private temperance.protobuf.Query.Request.Get buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public temperance.protobuf.Query.Request.Get buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          temperance.protobuf.Query.Request.Get returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof temperance.protobuf.Query.Request.Get) {
            return mergeFrom((temperance.protobuf.Query.Request.Get)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(temperance.protobuf.Query.Request.Get other) {
          if (other == temperance.protobuf.Query.Request.Get.getDefaultInstance()) return this;
          if (other.hasQuery()) {
            setQuery(other.getQuery());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setQuery(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required string query = 1;
        public boolean hasQuery() {
          return result.hasQuery();
        }
        public java.lang.String getQuery() {
          return result.getQuery();
        }
        public Builder setQuery(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasQuery = true;
          result.query_ = value;
          return this;
        }
        public Builder clearQuery() {
          result.hasQuery = false;
          result.query_ = getDefaultInstance().getQuery();
          return this;
        }
      }
      
      static {
        temperance.protobuf.Query.getDescriptor();
      }
      
      static {
        temperance.protobuf.Query.internalForceInit();
      }
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static temperance.protobuf.Query.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Query.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Query.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Query.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Query.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Query.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Query.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static temperance.protobuf.Query.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Query.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Query.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(temperance.protobuf.Query.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private temperance.protobuf.Query.Request result;
      
      // Construct using temperance.protobuf.Query.Request.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new temperance.protobuf.Query.Request();
        return builder;
      }
      
      protected temperance.protobuf.Query.Request internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new temperance.protobuf.Query.Request();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return temperance.protobuf.Query.Request.getDescriptor();
      }
      
      public temperance.protobuf.Query.Request getDefaultInstanceForType() {
        return temperance.protobuf.Query.Request.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public temperance.protobuf.Query.Request build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private temperance.protobuf.Query.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public temperance.protobuf.Query.Request buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        temperance.protobuf.Query.Request returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof temperance.protobuf.Query.Request) {
          return mergeFrom((temperance.protobuf.Query.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(temperance.protobuf.Query.Request other) {
        if (other == temperance.protobuf.Query.Request.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
    }
    
    static {
      temperance.protobuf.Query.getDescriptor();
    }
    
    static {
      temperance.protobuf.Query.internalForceInit();
    }
  }
  
  public static final class Response extends
      com.google.protobuf.GeneratedMessage {
    // Use Response.newBuilder() to construct.
    private Response() {}
    
    private static final Response defaultInstance = new Response();
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return temperance.protobuf.Query.internal_static_temperance_protobuf_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return temperance.protobuf.Query.internal_static_temperance_protobuf_Response_fieldAccessorTable;
    }
    
    public static final class Get extends
        com.google.protobuf.GeneratedMessage {
      // Use Get.newBuilder() to construct.
      private Get() {}
      
      private static final Get defaultInstance = new Get();
      public static Get getDefaultInstance() {
        return defaultInstance;
      }
      
      public Get getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temperance.protobuf.Query.internal_static_temperance_protobuf_Response_Get_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temperance.protobuf.Query.internal_static_temperance_protobuf_Response_Get_fieldAccessorTable;
      }
      
      // repeated string values = 1;
      public static final int VALUES_FIELD_NUMBER = 1;
      private java.util.List<java.lang.String> values_ =
        java.util.Collections.emptyList();
      public java.util.List<java.lang.String> getValuesList() {
        return values_;
      }
      public int getValuesCount() { return values_.size(); }
      public java.lang.String getValues(int index) {
        return values_.get(index);
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (java.lang.String element : getValuesList()) {
          output.writeString(1, element);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        {
          int dataSize = 0;
          for (java.lang.String element : getValuesList()) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeStringSizeNoTag(element);
          }
          size += dataSize;
          size += 1 * getValuesList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static temperance.protobuf.Query.Response.Get parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Query.Response.Get parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Query.Response.Get parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Query.Response.Get parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Query.Response.Get parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Query.Response.Get parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Query.Response.Get parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static temperance.protobuf.Query.Response.Get parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Query.Response.Get parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Query.Response.Get parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(temperance.protobuf.Query.Response.Get prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private temperance.protobuf.Query.Response.Get result;
        
        // Construct using temperance.protobuf.Query.Response.Get.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new temperance.protobuf.Query.Response.Get();
          return builder;
        }
        
        protected temperance.protobuf.Query.Response.Get internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new temperance.protobuf.Query.Response.Get();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return temperance.protobuf.Query.Response.Get.getDescriptor();
        }
        
        public temperance.protobuf.Query.Response.Get getDefaultInstanceForType() {
          return temperance.protobuf.Query.Response.Get.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public temperance.protobuf.Query.Response.Get build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private temperance.protobuf.Query.Response.Get buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public temperance.protobuf.Query.Response.Get buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          if (result.values_ != java.util.Collections.EMPTY_LIST) {
            result.values_ =
              java.util.Collections.unmodifiableList(result.values_);
          }
          temperance.protobuf.Query.Response.Get returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof temperance.protobuf.Query.Response.Get) {
            return mergeFrom((temperance.protobuf.Query.Response.Get)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(temperance.protobuf.Query.Response.Get other) {
          if (other == temperance.protobuf.Query.Response.Get.getDefaultInstance()) return this;
          if (!other.values_.isEmpty()) {
            if (result.values_.isEmpty()) {
              result.values_ = new java.util.ArrayList<java.lang.String>();
            }
            result.values_.addAll(other.values_);
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                addValues(input.readString());
                break;
              }
            }
          }
        }
        
        
        // repeated string values = 1;
        public java.util.List<java.lang.String> getValuesList() {
          return java.util.Collections.unmodifiableList(result.values_);
        }
        public int getValuesCount() {
          return result.getValuesCount();
        }
        public java.lang.String getValues(int index) {
          return result.getValues(index);
        }
        public Builder setValues(int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.values_.set(index, value);
          return this;
        }
        public Builder addValues(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  if (result.values_.isEmpty()) {
            result.values_ = new java.util.ArrayList<java.lang.String>();
          }
          result.values_.add(value);
          return this;
        }
        public Builder addAllValues(
            java.lang.Iterable<? extends java.lang.String> values) {
          if (result.values_.isEmpty()) {
            result.values_ = new java.util.ArrayList<java.lang.String>();
          }
          super.addAll(values, result.values_);
          return this;
        }
        public Builder clearValues() {
          result.values_ = java.util.Collections.emptyList();
          return this;
        }
      }
      
      static {
        temperance.protobuf.Query.getDescriptor();
      }
      
      static {
        temperance.protobuf.Query.internalForceInit();
      }
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static temperance.protobuf.Query.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Query.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Query.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Query.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Query.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Query.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Query.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static temperance.protobuf.Query.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Query.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Query.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(temperance.protobuf.Query.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private temperance.protobuf.Query.Response result;
      
      // Construct using temperance.protobuf.Query.Response.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new temperance.protobuf.Query.Response();
        return builder;
      }
      
      protected temperance.protobuf.Query.Response internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new temperance.protobuf.Query.Response();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return temperance.protobuf.Query.Response.getDescriptor();
      }
      
      public temperance.protobuf.Query.Response getDefaultInstanceForType() {
        return temperance.protobuf.Query.Response.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public temperance.protobuf.Query.Response build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private temperance.protobuf.Query.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public temperance.protobuf.Query.Response buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        temperance.protobuf.Query.Response returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof temperance.protobuf.Query.Response) {
          return mergeFrom((temperance.protobuf.Query.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(temperance.protobuf.Query.Response other) {
        if (other == temperance.protobuf.Query.Response.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
    }
    
    static {
      temperance.protobuf.Query.getDescriptor();
    }
    
    static {
      temperance.protobuf.Query.internalForceInit();
    }
  }
  
  public static abstract class QueryService
      implements com.google.protobuf.Service {
    protected QueryService() {}
    
    public interface Interface {
      public abstract void get(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Query.Request.Get request,
          com.google.protobuf.RpcCallback<temperance.protobuf.Query.Response.Get> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new QueryService() {
        @Override
        public  void get(
            com.google.protobuf.RpcController controller,
            temperance.protobuf.Query.Request.Get request,
            com.google.protobuf.RpcCallback<temperance.protobuf.Query.Response.Get> done) {
          impl.get(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.get(controller, (temperance.protobuf.Query.Request.Get)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return temperance.protobuf.Query.Request.Get.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return temperance.protobuf.Query.Response.Get.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void get(
        com.google.protobuf.RpcController controller,
        temperance.protobuf.Query.Request.Get request,
        com.google.protobuf.RpcCallback<temperance.protobuf.Query.Response.Get> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return temperance.protobuf.Query.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.get(controller, (temperance.protobuf.Query.Request.Get)request,
            com.google.protobuf.RpcUtil.<temperance.protobuf.Query.Response.Get>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return temperance.protobuf.Query.Request.Get.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return temperance.protobuf.Query.Response.Get.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends temperance.protobuf.Query.QueryService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void get(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Query.Request.Get request,
          com.google.protobuf.RpcCallback<temperance.protobuf.Query.Response.Get> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          temperance.protobuf.Query.Response.Get.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            temperance.protobuf.Query.Response.Get.class,
            temperance.protobuf.Query.Response.Get.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public temperance.protobuf.Query.Response.Get get(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Query.Request.Get request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public temperance.protobuf.Query.Response.Get get(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Query.Request.Get request)
          throws com.google.protobuf.ServiceException {
        return (temperance.protobuf.Query.Response.Get) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          temperance.protobuf.Query.Response.Get.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Request_Get_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Request_Get_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Response_Get_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Response_Get_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Query.proto\022\023temperance.protobuf\"\037\n\007Re" +
      "quest\032\024\n\003Get\022\r\n\005query\030\001 \002(\t\"!\n\010Response\032" +
      "\025\n\003Get\022\016\n\006values\030\001 \003(\t2Z\n\014QueryService\022J" +
      "\n\003get\022 .temperance.protobuf.Request.Get\032" +
      "!.temperance.protobuf.Response.GetB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_temperance_protobuf_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_temperance_protobuf_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Request_descriptor,
              new java.lang.String[] { },
              temperance.protobuf.Query.Request.class,
              temperance.protobuf.Query.Request.Builder.class);
          internal_static_temperance_protobuf_Request_Get_descriptor =
            internal_static_temperance_protobuf_Request_descriptor.getNestedTypes().get(0);
          internal_static_temperance_protobuf_Request_Get_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Request_Get_descriptor,
              new java.lang.String[] { "Query", },
              temperance.protobuf.Query.Request.Get.class,
              temperance.protobuf.Query.Request.Get.Builder.class);
          internal_static_temperance_protobuf_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_temperance_protobuf_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Response_descriptor,
              new java.lang.String[] { },
              temperance.protobuf.Query.Response.class,
              temperance.protobuf.Query.Response.Builder.class);
          internal_static_temperance_protobuf_Response_Get_descriptor =
            internal_static_temperance_protobuf_Response_descriptor.getNestedTypes().get(0);
          internal_static_temperance_protobuf_Response_Get_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Response_Get_descriptor,
              new java.lang.String[] { "Values", },
              temperance.protobuf.Query.Response.Get.class,
              temperance.protobuf.Query.Response.Get.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
