// Generated by the protocol buffer compiler.  DO NOT EDIT!

package temperance.protobuf;

public final class Queue {
  private Queue() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage {
    // Use Request.newBuilder() to construct.
    private Request() {}
    
    private static final Request defaultInstance = new Request();
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return temperance.protobuf.Queue.internal_static_temperance_protobuf_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return temperance.protobuf.Queue.internal_static_temperance_protobuf_Request_fieldAccessorTable;
    }
    
    public static final class Enqueue extends
        com.google.protobuf.GeneratedMessage {
      // Use Enqueue.newBuilder() to construct.
      private Enqueue() {}
      
      private static final Enqueue defaultInstance = new Enqueue();
      public static Enqueue getDefaultInstance() {
        return defaultInstance;
      }
      
      public Enqueue getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temperance.protobuf.Queue.internal_static_temperance_protobuf_Request_Enqueue_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temperance.protobuf.Queue.internal_static_temperance_protobuf_Request_Enqueue_fieldAccessorTable;
      }
      
      // required string key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private boolean hasKey;
      private java.lang.String key_ = "";
      public boolean hasKey() { return hasKey; }
      public java.lang.String getKey() { return key_; }
      
      // required string value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private boolean hasValue;
      private java.lang.String value_ = "";
      public boolean hasValue() { return hasValue; }
      public java.lang.String getValue() { return value_; }
      
      // optional uint32 expire = 3 [default = 86400];
      public static final int EXPIRE_FIELD_NUMBER = 3;
      private boolean hasExpire;
      private int expire_ = 86400;
      public boolean hasExpire() { return hasExpire; }
      public int getExpire() { return expire_; }
      
      public final boolean isInitialized() {
        if (!hasKey) return false;
        if (!hasValue) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasKey()) {
          output.writeString(1, getKey());
        }
        if (hasValue()) {
          output.writeString(2, getValue());
        }
        if (hasExpire()) {
          output.writeUInt32(3, getExpire());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasKey()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getKey());
        }
        if (hasValue()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getValue());
        }
        if (hasExpire()) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(3, getExpire());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static temperance.protobuf.Queue.Request.Enqueue parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Enqueue parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Enqueue parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Enqueue parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Enqueue parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Enqueue parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Enqueue parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Enqueue parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Enqueue parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Enqueue parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(temperance.protobuf.Queue.Request.Enqueue prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private temperance.protobuf.Queue.Request.Enqueue result;
        
        // Construct using temperance.protobuf.Queue.Request.Enqueue.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new temperance.protobuf.Queue.Request.Enqueue();
          return builder;
        }
        
        protected temperance.protobuf.Queue.Request.Enqueue internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new temperance.protobuf.Queue.Request.Enqueue();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return temperance.protobuf.Queue.Request.Enqueue.getDescriptor();
        }
        
        public temperance.protobuf.Queue.Request.Enqueue getDefaultInstanceForType() {
          return temperance.protobuf.Queue.Request.Enqueue.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public temperance.protobuf.Queue.Request.Enqueue build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private temperance.protobuf.Queue.Request.Enqueue buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public temperance.protobuf.Queue.Request.Enqueue buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          temperance.protobuf.Queue.Request.Enqueue returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof temperance.protobuf.Queue.Request.Enqueue) {
            return mergeFrom((temperance.protobuf.Queue.Request.Enqueue)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(temperance.protobuf.Queue.Request.Enqueue other) {
          if (other == temperance.protobuf.Queue.Request.Enqueue.getDefaultInstance()) return this;
          if (other.hasKey()) {
            setKey(other.getKey());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          if (other.hasExpire()) {
            setExpire(other.getExpire());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setKey(input.readString());
                break;
              }
              case 18: {
                setValue(input.readString());
                break;
              }
              case 24: {
                setExpire(input.readUInt32());
                break;
              }
            }
          }
        }
        
        
        // required string key = 1;
        public boolean hasKey() {
          return result.hasKey();
        }
        public java.lang.String getKey() {
          return result.getKey();
        }
        public Builder setKey(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
          result.key_ = value;
          return this;
        }
        public Builder clearKey() {
          result.hasKey = false;
          result.key_ = getDefaultInstance().getKey();
          return this;
        }
        
        // required string value = 2;
        public boolean hasValue() {
          return result.hasValue();
        }
        public java.lang.String getValue() {
          return result.getValue();
        }
        public Builder setValue(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasValue = true;
          result.value_ = value;
          return this;
        }
        public Builder clearValue() {
          result.hasValue = false;
          result.value_ = getDefaultInstance().getValue();
          return this;
        }
        
        // optional uint32 expire = 3 [default = 86400];
        public boolean hasExpire() {
          return result.hasExpire();
        }
        public int getExpire() {
          return result.getExpire();
        }
        public Builder setExpire(int value) {
          result.hasExpire = true;
          result.expire_ = value;
          return this;
        }
        public Builder clearExpire() {
          result.hasExpire = false;
          result.expire_ = 86400;
          return this;
        }
      }
      
      static {
        temperance.protobuf.Queue.getDescriptor();
      }
      
      static {
        temperance.protobuf.Queue.internalForceInit();
      }
    }
    
    public static final class Dequeue extends
        com.google.protobuf.GeneratedMessage {
      // Use Dequeue.newBuilder() to construct.
      private Dequeue() {}
      
      private static final Dequeue defaultInstance = new Dequeue();
      public static Dequeue getDefaultInstance() {
        return defaultInstance;
      }
      
      public Dequeue getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temperance.protobuf.Queue.internal_static_temperance_protobuf_Request_Dequeue_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temperance.protobuf.Queue.internal_static_temperance_protobuf_Request_Dequeue_fieldAccessorTable;
      }
      
      // required string key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private boolean hasKey;
      private java.lang.String key_ = "";
      public boolean hasKey() { return hasKey; }
      public java.lang.String getKey() { return key_; }
      
      // optional uint32 timeout = 2 [default = 10];
      public static final int TIMEOUT_FIELD_NUMBER = 2;
      private boolean hasTimeout;
      private int timeout_ = 10;
      public boolean hasTimeout() { return hasTimeout; }
      public int getTimeout() { return timeout_; }
      
      public final boolean isInitialized() {
        if (!hasKey) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasKey()) {
          output.writeString(1, getKey());
        }
        if (hasTimeout()) {
          output.writeUInt32(2, getTimeout());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasKey()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getKey());
        }
        if (hasTimeout()) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, getTimeout());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static temperance.protobuf.Queue.Request.Dequeue parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Dequeue parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Dequeue parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Dequeue parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Dequeue parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Dequeue parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Dequeue parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Dequeue parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Dequeue parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Queue.Request.Dequeue parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(temperance.protobuf.Queue.Request.Dequeue prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private temperance.protobuf.Queue.Request.Dequeue result;
        
        // Construct using temperance.protobuf.Queue.Request.Dequeue.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new temperance.protobuf.Queue.Request.Dequeue();
          return builder;
        }
        
        protected temperance.protobuf.Queue.Request.Dequeue internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new temperance.protobuf.Queue.Request.Dequeue();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return temperance.protobuf.Queue.Request.Dequeue.getDescriptor();
        }
        
        public temperance.protobuf.Queue.Request.Dequeue getDefaultInstanceForType() {
          return temperance.protobuf.Queue.Request.Dequeue.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public temperance.protobuf.Queue.Request.Dequeue build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private temperance.protobuf.Queue.Request.Dequeue buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public temperance.protobuf.Queue.Request.Dequeue buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          temperance.protobuf.Queue.Request.Dequeue returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof temperance.protobuf.Queue.Request.Dequeue) {
            return mergeFrom((temperance.protobuf.Queue.Request.Dequeue)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(temperance.protobuf.Queue.Request.Dequeue other) {
          if (other == temperance.protobuf.Queue.Request.Dequeue.getDefaultInstance()) return this;
          if (other.hasKey()) {
            setKey(other.getKey());
          }
          if (other.hasTimeout()) {
            setTimeout(other.getTimeout());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setKey(input.readString());
                break;
              }
              case 16: {
                setTimeout(input.readUInt32());
                break;
              }
            }
          }
        }
        
        
        // required string key = 1;
        public boolean hasKey() {
          return result.hasKey();
        }
        public java.lang.String getKey() {
          return result.getKey();
        }
        public Builder setKey(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
          result.key_ = value;
          return this;
        }
        public Builder clearKey() {
          result.hasKey = false;
          result.key_ = getDefaultInstance().getKey();
          return this;
        }
        
        // optional uint32 timeout = 2 [default = 10];
        public boolean hasTimeout() {
          return result.hasTimeout();
        }
        public int getTimeout() {
          return result.getTimeout();
        }
        public Builder setTimeout(int value) {
          result.hasTimeout = true;
          result.timeout_ = value;
          return this;
        }
        public Builder clearTimeout() {
          result.hasTimeout = false;
          result.timeout_ = 10;
          return this;
        }
      }
      
      static {
        temperance.protobuf.Queue.getDescriptor();
      }
      
      static {
        temperance.protobuf.Queue.internalForceInit();
      }
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static temperance.protobuf.Queue.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Queue.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Queue.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Queue.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Queue.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Queue.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Queue.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static temperance.protobuf.Queue.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Queue.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Queue.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(temperance.protobuf.Queue.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private temperance.protobuf.Queue.Request result;
      
      // Construct using temperance.protobuf.Queue.Request.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new temperance.protobuf.Queue.Request();
        return builder;
      }
      
      protected temperance.protobuf.Queue.Request internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new temperance.protobuf.Queue.Request();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return temperance.protobuf.Queue.Request.getDescriptor();
      }
      
      public temperance.protobuf.Queue.Request getDefaultInstanceForType() {
        return temperance.protobuf.Queue.Request.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public temperance.protobuf.Queue.Request build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private temperance.protobuf.Queue.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public temperance.protobuf.Queue.Request buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        temperance.protobuf.Queue.Request returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof temperance.protobuf.Queue.Request) {
          return mergeFrom((temperance.protobuf.Queue.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(temperance.protobuf.Queue.Request other) {
        if (other == temperance.protobuf.Queue.Request.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
    }
    
    static {
      temperance.protobuf.Queue.getDescriptor();
    }
    
    static {
      temperance.protobuf.Queue.internalForceInit();
    }
  }
  
  public static final class Response extends
      com.google.protobuf.GeneratedMessage {
    // Use Response.newBuilder() to construct.
    private Response() {}
    
    private static final Response defaultInstance = new Response();
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return temperance.protobuf.Queue.internal_static_temperance_protobuf_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return temperance.protobuf.Queue.internal_static_temperance_protobuf_Response_fieldAccessorTable;
    }
    
    public static final class Enqueue extends
        com.google.protobuf.GeneratedMessage {
      // Use Enqueue.newBuilder() to construct.
      private Enqueue() {}
      
      private static final Enqueue defaultInstance = new Enqueue();
      public static Enqueue getDefaultInstance() {
        return defaultInstance;
      }
      
      public Enqueue getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temperance.protobuf.Queue.internal_static_temperance_protobuf_Response_Enqueue_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temperance.protobuf.Queue.internal_static_temperance_protobuf_Response_Enqueue_fieldAccessorTable;
      }
      
      // required bool succeed = 1;
      public static final int SUCCEED_FIELD_NUMBER = 1;
      private boolean hasSucceed;
      private boolean succeed_ = false;
      public boolean hasSucceed() { return hasSucceed; }
      public boolean getSucceed() { return succeed_; }
      
      public final boolean isInitialized() {
        if (!hasSucceed) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasSucceed()) {
          output.writeBool(1, getSucceed());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasSucceed()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(1, getSucceed());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static temperance.protobuf.Queue.Response.Enqueue parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Enqueue parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Enqueue parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Enqueue parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Enqueue parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Enqueue parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Enqueue parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Enqueue parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Enqueue parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Enqueue parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(temperance.protobuf.Queue.Response.Enqueue prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private temperance.protobuf.Queue.Response.Enqueue result;
        
        // Construct using temperance.protobuf.Queue.Response.Enqueue.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new temperance.protobuf.Queue.Response.Enqueue();
          return builder;
        }
        
        protected temperance.protobuf.Queue.Response.Enqueue internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new temperance.protobuf.Queue.Response.Enqueue();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return temperance.protobuf.Queue.Response.Enqueue.getDescriptor();
        }
        
        public temperance.protobuf.Queue.Response.Enqueue getDefaultInstanceForType() {
          return temperance.protobuf.Queue.Response.Enqueue.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public temperance.protobuf.Queue.Response.Enqueue build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private temperance.protobuf.Queue.Response.Enqueue buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public temperance.protobuf.Queue.Response.Enqueue buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          temperance.protobuf.Queue.Response.Enqueue returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof temperance.protobuf.Queue.Response.Enqueue) {
            return mergeFrom((temperance.protobuf.Queue.Response.Enqueue)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(temperance.protobuf.Queue.Response.Enqueue other) {
          if (other == temperance.protobuf.Queue.Response.Enqueue.getDefaultInstance()) return this;
          if (other.hasSucceed()) {
            setSucceed(other.getSucceed());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 8: {
                setSucceed(input.readBool());
                break;
              }
            }
          }
        }
        
        
        // required bool succeed = 1;
        public boolean hasSucceed() {
          return result.hasSucceed();
        }
        public boolean getSucceed() {
          return result.getSucceed();
        }
        public Builder setSucceed(boolean value) {
          result.hasSucceed = true;
          result.succeed_ = value;
          return this;
        }
        public Builder clearSucceed() {
          result.hasSucceed = false;
          result.succeed_ = false;
          return this;
        }
      }
      
      static {
        temperance.protobuf.Queue.getDescriptor();
      }
      
      static {
        temperance.protobuf.Queue.internalForceInit();
      }
    }
    
    public static final class Dequeue extends
        com.google.protobuf.GeneratedMessage {
      // Use Dequeue.newBuilder() to construct.
      private Dequeue() {}
      
      private static final Dequeue defaultInstance = new Dequeue();
      public static Dequeue getDefaultInstance() {
        return defaultInstance;
      }
      
      public Dequeue getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temperance.protobuf.Queue.internal_static_temperance_protobuf_Response_Dequeue_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temperance.protobuf.Queue.internal_static_temperance_protobuf_Response_Dequeue_fieldAccessorTable;
      }
      
      // required string value = 1;
      public static final int VALUE_FIELD_NUMBER = 1;
      private boolean hasValue;
      private java.lang.String value_ = "";
      public boolean hasValue() { return hasValue; }
      public java.lang.String getValue() { return value_; }
      
      public final boolean isInitialized() {
        if (!hasValue) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasValue()) {
          output.writeString(1, getValue());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasValue()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getValue());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static temperance.protobuf.Queue.Response.Dequeue parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Dequeue parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Dequeue parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Dequeue parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Dequeue parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Dequeue parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Dequeue parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Dequeue parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Dequeue parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Queue.Response.Dequeue parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(temperance.protobuf.Queue.Response.Dequeue prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private temperance.protobuf.Queue.Response.Dequeue result;
        
        // Construct using temperance.protobuf.Queue.Response.Dequeue.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new temperance.protobuf.Queue.Response.Dequeue();
          return builder;
        }
        
        protected temperance.protobuf.Queue.Response.Dequeue internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new temperance.protobuf.Queue.Response.Dequeue();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return temperance.protobuf.Queue.Response.Dequeue.getDescriptor();
        }
        
        public temperance.protobuf.Queue.Response.Dequeue getDefaultInstanceForType() {
          return temperance.protobuf.Queue.Response.Dequeue.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public temperance.protobuf.Queue.Response.Dequeue build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private temperance.protobuf.Queue.Response.Dequeue buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public temperance.protobuf.Queue.Response.Dequeue buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          temperance.protobuf.Queue.Response.Dequeue returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof temperance.protobuf.Queue.Response.Dequeue) {
            return mergeFrom((temperance.protobuf.Queue.Response.Dequeue)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(temperance.protobuf.Queue.Response.Dequeue other) {
          if (other == temperance.protobuf.Queue.Response.Dequeue.getDefaultInstance()) return this;
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setValue(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required string value = 1;
        public boolean hasValue() {
          return result.hasValue();
        }
        public java.lang.String getValue() {
          return result.getValue();
        }
        public Builder setValue(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasValue = true;
          result.value_ = value;
          return this;
        }
        public Builder clearValue() {
          result.hasValue = false;
          result.value_ = getDefaultInstance().getValue();
          return this;
        }
      }
      
      static {
        temperance.protobuf.Queue.getDescriptor();
      }
      
      static {
        temperance.protobuf.Queue.internalForceInit();
      }
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static temperance.protobuf.Queue.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Queue.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Queue.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Queue.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Queue.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Queue.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Queue.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static temperance.protobuf.Queue.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Queue.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Queue.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(temperance.protobuf.Queue.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private temperance.protobuf.Queue.Response result;
      
      // Construct using temperance.protobuf.Queue.Response.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new temperance.protobuf.Queue.Response();
        return builder;
      }
      
      protected temperance.protobuf.Queue.Response internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new temperance.protobuf.Queue.Response();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return temperance.protobuf.Queue.Response.getDescriptor();
      }
      
      public temperance.protobuf.Queue.Response getDefaultInstanceForType() {
        return temperance.protobuf.Queue.Response.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public temperance.protobuf.Queue.Response build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private temperance.protobuf.Queue.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public temperance.protobuf.Queue.Response buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        temperance.protobuf.Queue.Response returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof temperance.protobuf.Queue.Response) {
          return mergeFrom((temperance.protobuf.Queue.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(temperance.protobuf.Queue.Response other) {
        if (other == temperance.protobuf.Queue.Response.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
    }
    
    static {
      temperance.protobuf.Queue.getDescriptor();
    }
    
    static {
      temperance.protobuf.Queue.internalForceInit();
    }
  }
  
  public static abstract class QueueService
      implements com.google.protobuf.Service {
    protected QueueService() {}
    
    public interface Interface {
      public abstract void enqueue(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Queue.Request.Enqueue request,
          com.google.protobuf.RpcCallback<temperance.protobuf.Queue.Response.Enqueue> done);
      
      public abstract void dequeue(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Queue.Request.Dequeue request,
          com.google.protobuf.RpcCallback<temperance.protobuf.Queue.Response.Dequeue> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new QueueService() {
        @Override
        public  void enqueue(
            com.google.protobuf.RpcController controller,
            temperance.protobuf.Queue.Request.Enqueue request,
            com.google.protobuf.RpcCallback<temperance.protobuf.Queue.Response.Enqueue> done) {
          impl.enqueue(controller, request, done);
        }
        
        @Override
        public  void dequeue(
            com.google.protobuf.RpcController controller,
            temperance.protobuf.Queue.Request.Dequeue request,
            com.google.protobuf.RpcCallback<temperance.protobuf.Queue.Response.Dequeue> done) {
          impl.dequeue(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.enqueue(controller, (temperance.protobuf.Queue.Request.Enqueue)request);
            case 1:
              return impl.dequeue(controller, (temperance.protobuf.Queue.Request.Dequeue)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return temperance.protobuf.Queue.Request.Enqueue.getDefaultInstance();
            case 1:
              return temperance.protobuf.Queue.Request.Dequeue.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return temperance.protobuf.Queue.Response.Enqueue.getDefaultInstance();
            case 1:
              return temperance.protobuf.Queue.Response.Dequeue.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void enqueue(
        com.google.protobuf.RpcController controller,
        temperance.protobuf.Queue.Request.Enqueue request,
        com.google.protobuf.RpcCallback<temperance.protobuf.Queue.Response.Enqueue> done);
    
    public abstract void dequeue(
        com.google.protobuf.RpcController controller,
        temperance.protobuf.Queue.Request.Dequeue request,
        com.google.protobuf.RpcCallback<temperance.protobuf.Queue.Response.Dequeue> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return temperance.protobuf.Queue.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.enqueue(controller, (temperance.protobuf.Queue.Request.Enqueue)request,
            com.google.protobuf.RpcUtil.<temperance.protobuf.Queue.Response.Enqueue>specializeCallback(
              done));
          return;
        case 1:
          this.dequeue(controller, (temperance.protobuf.Queue.Request.Dequeue)request,
            com.google.protobuf.RpcUtil.<temperance.protobuf.Queue.Response.Dequeue>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return temperance.protobuf.Queue.Request.Enqueue.getDefaultInstance();
        case 1:
          return temperance.protobuf.Queue.Request.Dequeue.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return temperance.protobuf.Queue.Response.Enqueue.getDefaultInstance();
        case 1:
          return temperance.protobuf.Queue.Response.Dequeue.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends temperance.protobuf.Queue.QueueService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void enqueue(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Queue.Request.Enqueue request,
          com.google.protobuf.RpcCallback<temperance.protobuf.Queue.Response.Enqueue> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          temperance.protobuf.Queue.Response.Enqueue.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            temperance.protobuf.Queue.Response.Enqueue.class,
            temperance.protobuf.Queue.Response.Enqueue.getDefaultInstance()));
      }
      
      public  void dequeue(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Queue.Request.Dequeue request,
          com.google.protobuf.RpcCallback<temperance.protobuf.Queue.Response.Dequeue> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          temperance.protobuf.Queue.Response.Dequeue.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            temperance.protobuf.Queue.Response.Dequeue.class,
            temperance.protobuf.Queue.Response.Dequeue.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public temperance.protobuf.Queue.Response.Enqueue enqueue(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Queue.Request.Enqueue request)
          throws com.google.protobuf.ServiceException;
      
      public temperance.protobuf.Queue.Response.Dequeue dequeue(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Queue.Request.Dequeue request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public temperance.protobuf.Queue.Response.Enqueue enqueue(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Queue.Request.Enqueue request)
          throws com.google.protobuf.ServiceException {
        return (temperance.protobuf.Queue.Response.Enqueue) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          temperance.protobuf.Queue.Response.Enqueue.getDefaultInstance());
      }
      
      
      public temperance.protobuf.Queue.Response.Dequeue dequeue(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Queue.Request.Dequeue request)
          throws com.google.protobuf.ServiceException {
        return (temperance.protobuf.Queue.Response.Dequeue) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          temperance.protobuf.Queue.Response.Dequeue.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Request_Enqueue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Request_Enqueue_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Request_Dequeue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Request_Dequeue_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Response_Enqueue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Response_Enqueue_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Response_Dequeue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Response_Dequeue_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Queue.proto\022\023temperance.protobuf\"t\n\007Re" +
      "quest\032<\n\007Enqueue\022\013\n\003key\030\001 \002(\t\022\r\n\005value\030\002" +
      " \002(\t\022\025\n\006expire\030\003 \001(\r:\00586400\032+\n\007Dequeue\022\013" +
      "\n\003key\030\001 \002(\t\022\023\n\007timeout\030\002 \001(\r:\00210\"@\n\010Resp" +
      "onse\032\032\n\007Enqueue\022\017\n\007succeed\030\001 \002(\010\032\030\n\007Dequ" +
      "eue\022\r\n\005value\030\001 \002(\t2\276\001\n\014QueueService\022V\n\007e" +
      "nqueue\022$.temperance.protobuf.Request.Enq" +
      "ueue\032%.temperance.protobuf.Response.Enqu" +
      "eue\022V\n\007dequeue\022$.temperance.protobuf.Req" +
      "uest.Dequeue\032%.temperance.protobuf.Respo",
      "nse.DequeueB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_temperance_protobuf_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_temperance_protobuf_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Request_descriptor,
              new java.lang.String[] { },
              temperance.protobuf.Queue.Request.class,
              temperance.protobuf.Queue.Request.Builder.class);
          internal_static_temperance_protobuf_Request_Enqueue_descriptor =
            internal_static_temperance_protobuf_Request_descriptor.getNestedTypes().get(0);
          internal_static_temperance_protobuf_Request_Enqueue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Request_Enqueue_descriptor,
              new java.lang.String[] { "Key", "Value", "Expire", },
              temperance.protobuf.Queue.Request.Enqueue.class,
              temperance.protobuf.Queue.Request.Enqueue.Builder.class);
          internal_static_temperance_protobuf_Request_Dequeue_descriptor =
            internal_static_temperance_protobuf_Request_descriptor.getNestedTypes().get(1);
          internal_static_temperance_protobuf_Request_Dequeue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Request_Dequeue_descriptor,
              new java.lang.String[] { "Key", "Timeout", },
              temperance.protobuf.Queue.Request.Dequeue.class,
              temperance.protobuf.Queue.Request.Dequeue.Builder.class);
          internal_static_temperance_protobuf_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_temperance_protobuf_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Response_descriptor,
              new java.lang.String[] { },
              temperance.protobuf.Queue.Response.class,
              temperance.protobuf.Queue.Response.Builder.class);
          internal_static_temperance_protobuf_Response_Enqueue_descriptor =
            internal_static_temperance_protobuf_Response_descriptor.getNestedTypes().get(0);
          internal_static_temperance_protobuf_Response_Enqueue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Response_Enqueue_descriptor,
              new java.lang.String[] { "Succeed", },
              temperance.protobuf.Queue.Response.Enqueue.class,
              temperance.protobuf.Queue.Response.Enqueue.Builder.class);
          internal_static_temperance_protobuf_Response_Dequeue_descriptor =
            internal_static_temperance_protobuf_Response_descriptor.getNestedTypes().get(1);
          internal_static_temperance_protobuf_Response_Dequeue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Response_Dequeue_descriptor,
              new java.lang.String[] { "Value", },
              temperance.protobuf.Queue.Response.Dequeue.class,
              temperance.protobuf.Queue.Response.Dequeue.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
