// Generated by the protocol buffer compiler.  DO NOT EDIT!

package temperance.protobuf;

public final class Temperance {
  private Temperance() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage {
    // Use Request.newBuilder() to construct.
    private Request() {}
    
    private static final Request defaultInstance = new Request();
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return temperance.protobuf.Temperance.internal_static_temperance_protobuf_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return temperance.protobuf.Temperance.internal_static_temperance_protobuf_Request_fieldAccessorTable;
    }
    
    public static final class Monitor extends
        com.google.protobuf.GeneratedMessage {
      // Use Monitor.newBuilder() to construct.
      private Monitor() {}
      
      private static final Monitor defaultInstance = new Monitor();
      public static Monitor getDefaultInstance() {
        return defaultInstance;
      }
      
      public Monitor getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temperance.protobuf.Temperance.internal_static_temperance_protobuf_Request_Monitor_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temperance.protobuf.Temperance.internal_static_temperance_protobuf_Request_Monitor_fieldAccessorTable;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static temperance.protobuf.Temperance.Request.Monitor parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Temperance.Request.Monitor parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Temperance.Request.Monitor parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Temperance.Request.Monitor parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Temperance.Request.Monitor parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Temperance.Request.Monitor parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Temperance.Request.Monitor parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static temperance.protobuf.Temperance.Request.Monitor parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Temperance.Request.Monitor parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Temperance.Request.Monitor parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(temperance.protobuf.Temperance.Request.Monitor prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private temperance.protobuf.Temperance.Request.Monitor result;
        
        // Construct using temperance.protobuf.Temperance.Request.Monitor.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new temperance.protobuf.Temperance.Request.Monitor();
          return builder;
        }
        
        protected temperance.protobuf.Temperance.Request.Monitor internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new temperance.protobuf.Temperance.Request.Monitor();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return temperance.protobuf.Temperance.Request.Monitor.getDescriptor();
        }
        
        public temperance.protobuf.Temperance.Request.Monitor getDefaultInstanceForType() {
          return temperance.protobuf.Temperance.Request.Monitor.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public temperance.protobuf.Temperance.Request.Monitor build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private temperance.protobuf.Temperance.Request.Monitor buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public temperance.protobuf.Temperance.Request.Monitor buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          temperance.protobuf.Temperance.Request.Monitor returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof temperance.protobuf.Temperance.Request.Monitor) {
            return mergeFrom((temperance.protobuf.Temperance.Request.Monitor)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(temperance.protobuf.Temperance.Request.Monitor other) {
          if (other == temperance.protobuf.Temperance.Request.Monitor.getDefaultInstance()) return this;
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
            }
          }
        }
        
      }
      
      static {
        temperance.protobuf.Temperance.getDescriptor();
      }
      
      static {
        temperance.protobuf.Temperance.internalForceInit();
      }
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static temperance.protobuf.Temperance.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Temperance.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Temperance.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Temperance.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Temperance.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Temperance.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Temperance.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static temperance.protobuf.Temperance.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Temperance.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Temperance.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(temperance.protobuf.Temperance.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private temperance.protobuf.Temperance.Request result;
      
      // Construct using temperance.protobuf.Temperance.Request.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new temperance.protobuf.Temperance.Request();
        return builder;
      }
      
      protected temperance.protobuf.Temperance.Request internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new temperance.protobuf.Temperance.Request();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return temperance.protobuf.Temperance.Request.getDescriptor();
      }
      
      public temperance.protobuf.Temperance.Request getDefaultInstanceForType() {
        return temperance.protobuf.Temperance.Request.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public temperance.protobuf.Temperance.Request build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private temperance.protobuf.Temperance.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public temperance.protobuf.Temperance.Request buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        temperance.protobuf.Temperance.Request returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof temperance.protobuf.Temperance.Request) {
          return mergeFrom((temperance.protobuf.Temperance.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(temperance.protobuf.Temperance.Request other) {
        if (other == temperance.protobuf.Temperance.Request.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
    }
    
    static {
      temperance.protobuf.Temperance.getDescriptor();
    }
    
    static {
      temperance.protobuf.Temperance.internalForceInit();
    }
  }
  
  public static final class Response extends
      com.google.protobuf.GeneratedMessage {
    // Use Response.newBuilder() to construct.
    private Response() {}
    
    private static final Response defaultInstance = new Response();
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return temperance.protobuf.Temperance.internal_static_temperance_protobuf_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return temperance.protobuf.Temperance.internal_static_temperance_protobuf_Response_fieldAccessorTable;
    }
    
    public static final class Monitor extends
        com.google.protobuf.GeneratedMessage {
      // Use Monitor.newBuilder() to construct.
      private Monitor() {}
      
      private static final Monitor defaultInstance = new Monitor();
      public static Monitor getDefaultInstance() {
        return defaultInstance;
      }
      
      public Monitor getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temperance.protobuf.Temperance.internal_static_temperance_protobuf_Response_Monitor_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temperance.protobuf.Temperance.internal_static_temperance_protobuf_Response_Monitor_fieldAccessorTable;
      }
      
      // required uint32 inProgressTasks = 1;
      public static final int INPROGRESSTASKS_FIELD_NUMBER = 1;
      private boolean hasInProgressTasks;
      private int inProgressTasks_ = 0;
      public boolean hasInProgressTasks() { return hasInProgressTasks; }
      public int getInProgressTasks() { return inProgressTasks_; }
      
      // required uint32 queuedTasks = 2;
      public static final int QUEUEDTASKS_FIELD_NUMBER = 2;
      private boolean hasQueuedTasks;
      private int queuedTasks_ = 0;
      public boolean hasQueuedTasks() { return hasQueuedTasks; }
      public int getQueuedTasks() { return queuedTasks_; }
      
      // required uint64 totalTasks = 3;
      public static final int TOTALTASKS_FIELD_NUMBER = 3;
      private boolean hasTotalTasks;
      private long totalTasks_ = 0L;
      public boolean hasTotalTasks() { return hasTotalTasks; }
      public long getTotalTasks() { return totalTasks_; }
      
      // required uint64 totalTime = 4;
      public static final int TOTALTIME_FIELD_NUMBER = 4;
      private boolean hasTotalTime;
      private long totalTime_ = 0L;
      public boolean hasTotalTime() { return hasTotalTime; }
      public long getTotalTime() { return totalTime_; }
      
      public final boolean isInitialized() {
        if (!hasInProgressTasks) return false;
        if (!hasQueuedTasks) return false;
        if (!hasTotalTasks) return false;
        if (!hasTotalTime) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasInProgressTasks()) {
          output.writeUInt32(1, getInProgressTasks());
        }
        if (hasQueuedTasks()) {
          output.writeUInt32(2, getQueuedTasks());
        }
        if (hasTotalTasks()) {
          output.writeUInt64(3, getTotalTasks());
        }
        if (hasTotalTime()) {
          output.writeUInt64(4, getTotalTime());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasInProgressTasks()) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, getInProgressTasks());
        }
        if (hasQueuedTasks()) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, getQueuedTasks());
        }
        if (hasTotalTasks()) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(3, getTotalTasks());
        }
        if (hasTotalTime()) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(4, getTotalTime());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static temperance.protobuf.Temperance.Response.Monitor parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Temperance.Response.Monitor parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Temperance.Response.Monitor parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static temperance.protobuf.Temperance.Response.Monitor parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Temperance.Response.Monitor parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Temperance.Response.Monitor parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Temperance.Response.Monitor parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static temperance.protobuf.Temperance.Response.Monitor parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static temperance.protobuf.Temperance.Response.Monitor parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static temperance.protobuf.Temperance.Response.Monitor parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(temperance.protobuf.Temperance.Response.Monitor prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private temperance.protobuf.Temperance.Response.Monitor result;
        
        // Construct using temperance.protobuf.Temperance.Response.Monitor.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new temperance.protobuf.Temperance.Response.Monitor();
          return builder;
        }
        
        protected temperance.protobuf.Temperance.Response.Monitor internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new temperance.protobuf.Temperance.Response.Monitor();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return temperance.protobuf.Temperance.Response.Monitor.getDescriptor();
        }
        
        public temperance.protobuf.Temperance.Response.Monitor getDefaultInstanceForType() {
          return temperance.protobuf.Temperance.Response.Monitor.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public temperance.protobuf.Temperance.Response.Monitor build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private temperance.protobuf.Temperance.Response.Monitor buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public temperance.protobuf.Temperance.Response.Monitor buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          temperance.protobuf.Temperance.Response.Monitor returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof temperance.protobuf.Temperance.Response.Monitor) {
            return mergeFrom((temperance.protobuf.Temperance.Response.Monitor)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(temperance.protobuf.Temperance.Response.Monitor other) {
          if (other == temperance.protobuf.Temperance.Response.Monitor.getDefaultInstance()) return this;
          if (other.hasInProgressTasks()) {
            setInProgressTasks(other.getInProgressTasks());
          }
          if (other.hasQueuedTasks()) {
            setQueuedTasks(other.getQueuedTasks());
          }
          if (other.hasTotalTasks()) {
            setTotalTasks(other.getTotalTasks());
          }
          if (other.hasTotalTime()) {
            setTotalTime(other.getTotalTime());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 8: {
                setInProgressTasks(input.readUInt32());
                break;
              }
              case 16: {
                setQueuedTasks(input.readUInt32());
                break;
              }
              case 24: {
                setTotalTasks(input.readUInt64());
                break;
              }
              case 32: {
                setTotalTime(input.readUInt64());
                break;
              }
            }
          }
        }
        
        
        // required uint32 inProgressTasks = 1;
        public boolean hasInProgressTasks() {
          return result.hasInProgressTasks();
        }
        public int getInProgressTasks() {
          return result.getInProgressTasks();
        }
        public Builder setInProgressTasks(int value) {
          result.hasInProgressTasks = true;
          result.inProgressTasks_ = value;
          return this;
        }
        public Builder clearInProgressTasks() {
          result.hasInProgressTasks = false;
          result.inProgressTasks_ = 0;
          return this;
        }
        
        // required uint32 queuedTasks = 2;
        public boolean hasQueuedTasks() {
          return result.hasQueuedTasks();
        }
        public int getQueuedTasks() {
          return result.getQueuedTasks();
        }
        public Builder setQueuedTasks(int value) {
          result.hasQueuedTasks = true;
          result.queuedTasks_ = value;
          return this;
        }
        public Builder clearQueuedTasks() {
          result.hasQueuedTasks = false;
          result.queuedTasks_ = 0;
          return this;
        }
        
        // required uint64 totalTasks = 3;
        public boolean hasTotalTasks() {
          return result.hasTotalTasks();
        }
        public long getTotalTasks() {
          return result.getTotalTasks();
        }
        public Builder setTotalTasks(long value) {
          result.hasTotalTasks = true;
          result.totalTasks_ = value;
          return this;
        }
        public Builder clearTotalTasks() {
          result.hasTotalTasks = false;
          result.totalTasks_ = 0L;
          return this;
        }
        
        // required uint64 totalTime = 4;
        public boolean hasTotalTime() {
          return result.hasTotalTime();
        }
        public long getTotalTime() {
          return result.getTotalTime();
        }
        public Builder setTotalTime(long value) {
          result.hasTotalTime = true;
          result.totalTime_ = value;
          return this;
        }
        public Builder clearTotalTime() {
          result.hasTotalTime = false;
          result.totalTime_ = 0L;
          return this;
        }
      }
      
      static {
        temperance.protobuf.Temperance.getDescriptor();
      }
      
      static {
        temperance.protobuf.Temperance.internalForceInit();
      }
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static temperance.protobuf.Temperance.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Temperance.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Temperance.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static temperance.protobuf.Temperance.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Temperance.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Temperance.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Temperance.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static temperance.protobuf.Temperance.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static temperance.protobuf.Temperance.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static temperance.protobuf.Temperance.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(temperance.protobuf.Temperance.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private temperance.protobuf.Temperance.Response result;
      
      // Construct using temperance.protobuf.Temperance.Response.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new temperance.protobuf.Temperance.Response();
        return builder;
      }
      
      protected temperance.protobuf.Temperance.Response internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new temperance.protobuf.Temperance.Response();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return temperance.protobuf.Temperance.Response.getDescriptor();
      }
      
      public temperance.protobuf.Temperance.Response getDefaultInstanceForType() {
        return temperance.protobuf.Temperance.Response.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public temperance.protobuf.Temperance.Response build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private temperance.protobuf.Temperance.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public temperance.protobuf.Temperance.Response buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        temperance.protobuf.Temperance.Response returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof temperance.protobuf.Temperance.Response) {
          return mergeFrom((temperance.protobuf.Temperance.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(temperance.protobuf.Temperance.Response other) {
        if (other == temperance.protobuf.Temperance.Response.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
    }
    
    static {
      temperance.protobuf.Temperance.getDescriptor();
    }
    
    static {
      temperance.protobuf.Temperance.internalForceInit();
    }
  }
  
  public static abstract class TemperanceService
      implements com.google.protobuf.Service {
    protected TemperanceService() {}
    
    public interface Interface {
      public abstract void monitor(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Temperance.Request.Monitor request,
          com.google.protobuf.RpcCallback<temperance.protobuf.Temperance.Response.Monitor> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new TemperanceService() {
        @Override
        public  void monitor(
            com.google.protobuf.RpcController controller,
            temperance.protobuf.Temperance.Request.Monitor request,
            com.google.protobuf.RpcCallback<temperance.protobuf.Temperance.Response.Monitor> done) {
          impl.monitor(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.monitor(controller, (temperance.protobuf.Temperance.Request.Monitor)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return temperance.protobuf.Temperance.Request.Monitor.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return temperance.protobuf.Temperance.Response.Monitor.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void monitor(
        com.google.protobuf.RpcController controller,
        temperance.protobuf.Temperance.Request.Monitor request,
        com.google.protobuf.RpcCallback<temperance.protobuf.Temperance.Response.Monitor> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return temperance.protobuf.Temperance.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.monitor(controller, (temperance.protobuf.Temperance.Request.Monitor)request,
            com.google.protobuf.RpcUtil.<temperance.protobuf.Temperance.Response.Monitor>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return temperance.protobuf.Temperance.Request.Monitor.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return temperance.protobuf.Temperance.Response.Monitor.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends temperance.protobuf.Temperance.TemperanceService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void monitor(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Temperance.Request.Monitor request,
          com.google.protobuf.RpcCallback<temperance.protobuf.Temperance.Response.Monitor> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          temperance.protobuf.Temperance.Response.Monitor.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            temperance.protobuf.Temperance.Response.Monitor.class,
            temperance.protobuf.Temperance.Response.Monitor.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public temperance.protobuf.Temperance.Response.Monitor monitor(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Temperance.Request.Monitor request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public temperance.protobuf.Temperance.Response.Monitor monitor(
          com.google.protobuf.RpcController controller,
          temperance.protobuf.Temperance.Request.Monitor request)
          throws com.google.protobuf.ServiceException {
        return (temperance.protobuf.Temperance.Response.Monitor) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          temperance.protobuf.Temperance.Response.Monitor.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Request_Monitor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Request_Monitor_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_temperance_protobuf_Response_Monitor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temperance_protobuf_Response_Monitor_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Temperance.proto\022\023temperance.protobuf\"" +
      "\024\n\007Request\032\t\n\007Monitor\"j\n\010Response\032^\n\007Mon" +
      "itor\022\027\n\017inProgressTasks\030\001 \002(\r\022\023\n\013queuedT" +
      "asks\030\002 \002(\r\022\022\n\ntotalTasks\030\003 \002(\004\022\021\n\ttotalT" +
      "ime\030\004 \002(\0042k\n\021TemperanceService\022V\n\007monito" +
      "r\022$.temperance.protobuf.Request.Monitor\032" +
      "%.temperance.protobuf.Response.MonitorB\002" +
      "H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_temperance_protobuf_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_temperance_protobuf_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Request_descriptor,
              new java.lang.String[] { },
              temperance.protobuf.Temperance.Request.class,
              temperance.protobuf.Temperance.Request.Builder.class);
          internal_static_temperance_protobuf_Request_Monitor_descriptor =
            internal_static_temperance_protobuf_Request_descriptor.getNestedTypes().get(0);
          internal_static_temperance_protobuf_Request_Monitor_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Request_Monitor_descriptor,
              new java.lang.String[] { },
              temperance.protobuf.Temperance.Request.Monitor.class,
              temperance.protobuf.Temperance.Request.Monitor.Builder.class);
          internal_static_temperance_protobuf_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_temperance_protobuf_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Response_descriptor,
              new java.lang.String[] { },
              temperance.protobuf.Temperance.Response.class,
              temperance.protobuf.Temperance.Response.Builder.class);
          internal_static_temperance_protobuf_Response_Monitor_descriptor =
            internal_static_temperance_protobuf_Response_descriptor.getNestedTypes().get(0);
          internal_static_temperance_protobuf_Response_Monitor_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_temperance_protobuf_Response_Monitor_descriptor,
              new java.lang.String[] { "InProgressTasks", "QueuedTasks", "TotalTasks", "TotalTime", },
              temperance.protobuf.Temperance.Response.Monitor.class,
              temperance.protobuf.Temperance.Response.Monitor.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
